dVAE_CFG:
  IMAGE_SIZE: 256

  NUM_TOKENS: 16384  # codebook image patch tokens
  NUM_LAYERS: 3
  NUM_RESNET_BLOCKS: 2
  SMOOTH_L1_LOSS: True
  EMB_DIM: 256
  HID_DIM: 256
  KL_LOSS_WEIGHT: 0
  STARTING_TEMP: 1.0
  TEMP_MIN: 0.5
  ANNEAL_RATE: 0.000001
  BASELINE: False